package dev.ios26.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates MODULES.md at the repo root. Module list is computed at configuration time
 * and passed as an input, so the task is configuration-cache safe.
 */
abstract class GenerateModulesDocTask : DefaultTask() {

    @get:Input
    abstract val rows: ListProperty<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val rows = rows.get().joinToString("\n")

        val doc = """
            # MODULES.md — Module Index (GENERATED)

            > Generated by `:generateModulesDoc` (build-logic `ios26.architecture`). Do not edit by hand.
            > Regenerate after module changes; CI checks freshness.

            | Module | Purpose | Depends on |
            |---|---|---|
            $rows
        """.trimIndent() + "\n"

        outputFile.get().asFile.writeText(doc)
    }
}

/** Renders markdown table rows for all explicit project subprojects (excluding build-logic). */
fun moduleDocsFor(project: Project): List<String> {
    val allowed = setOf("api", "implementation", "compileOnly")
    return project.rootProject.subprojects
        .filter { !it.path.startsWith(":build-logic") && it.buildFile.exists() }
        .map { module ->
            val purpose = module.file("README.md")
                .takeIf { it.exists() }
                ?.readLines()
                ?.firstOrNull { it.isNotBlank() && !it.startsWith("#") }
                ?.trim()
                ?: "(no README)"
            val deps = module.configurations
                .filter { it.name in allowed }
                .flatMap { it.dependencies }
                .filterIsInstance<ProjectDependency>()
                .map { it.path }
                .sorted()
                .joinToString(", ")
                .ifEmpty { "—" }
            "| `${module.path}` | $purpose | $deps |"
        }
}
